apiVersion: v1
kind: Service
metadata:
  name: clusterip-grup13
  namespace: grup13
spec:
  type: ClusterIP
  selector:
    app: web-grup13
    type: frontend
  ports:
  - port: 80
    targetPort: 80
  clusterIP: 10.96.13.101
